services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./targets/:/targets/
      - prometheus_data:/prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=auto-gomaxproc'
      - '--enable-feature=native-histograms'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000

  exporter:
    build:
      context: exporter
    container_name: pyexporter
    restart: always
    volumes:
      - ../../adapter/pull/exporter.py:/app/exporter.py
      - ./misc/exporters.sh:/app/exporters.sh
    command:
      - /bin/ash
      - /app/exporters.sh

volumes:
  prometheus_data: {}
  grafana_data: {}